apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: app-1
    type: front-end

spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 8080