apiVersion: v1
kind: Pod
metadata:
  labels:
    run: yellow
  name: yellow
spec:
  containers:
  - image: busybox
    imagePullPolicy: Always
    name: lemon
    command: ["sleep", "1000"]
  - image: redis
    name: gold