apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: example-container
    image: your-image:tag
    env:
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: example-configmap
          key: DATABASE_URL
    - name: API_KEY
      valueFrom:
        configMapKeyRef:
          name: example-configmap
          key: API_KEY