apiVersion: v1

kind: Pod

metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      command: ["sleep"] # ENTRYPOINT
      args: ["10"] # CMD